name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: 185.220.60.248
          remote-user: root
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: /var/www/vhosts/mintcreative.com/staging.mintcreative.com/sandbox/wp-content/themes/boilerplate
